version: "3.7"
services:
 sql-server-db:
  container_name: sql-server-dbdocker
  image: mcr.microsoft.com/mssql/server:2019-latest
  ports:
   - "1433:1433"
  environment:
   SA_PASSWORD: "super_duper_password!!123"
   ACCEPT_EULA: "y"